#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libzapojit
Version  : 0.0.3
Release  : 2
URL      : https://download.gnome.org/sources/libzapojit/0.0/libzapojit-0.0.3.tar.xz
Source0  : https://download.gnome.org/sources/libzapojit/0.0/libzapojit-0.0.3.tar.xz
Summary  : GLib/GObject wrapper for the SkyDrive and Hotmail REST APIs
Group    : Development/Tools
License  : LGPL-2.1
Requires: libzapojit-data = %{version}-%{release}
Requires: libzapojit-lib = %{version}-%{release}
Requires: libzapojit-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(rest-0.7)

%description
Zapojit - GLib/GObject wrapper for the SkyDrive and Hotmail REST APIs
=====================================================================

%package data
Summary: data components for the libzapojit package.
Group: Data

%description data
data components for the libzapojit package.


%package dev
Summary: dev components for the libzapojit package.
Group: Development
Requires: libzapojit-lib = %{version}-%{release}
Requires: libzapojit-data = %{version}-%{release}
Provides: libzapojit-devel = %{version}-%{release}
Requires: libzapojit = %{version}-%{release}

%description dev
dev components for the libzapojit package.


%package doc
Summary: doc components for the libzapojit package.
Group: Documentation

%description doc
doc components for the libzapojit package.


%package lib
Summary: lib components for the libzapojit package.
Group: Libraries
Requires: libzapojit-data = %{version}-%{release}
Requires: libzapojit-license = %{version}-%{release}

%description lib
lib components for the libzapojit package.


%package license
Summary: license components for the libzapojit package.
Group: Default

%description license
license components for the libzapojit package.


%prep
%setup -q -n libzapojit-0.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557019015
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557019015
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzapojit
cp COPYING %{buildroot}/usr/share/package-licenses/libzapojit/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Zpj-0.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libzapojit-0.0/zpj/zpj-authorization-domain.h
/usr/include/libzapojit-0.0/zpj/zpj-authorizer.h
/usr/include/libzapojit-0.0/zpj/zpj-goa-authorizer.h
/usr/include/libzapojit-0.0/zpj/zpj-skydrive-entry.h
/usr/include/libzapojit-0.0/zpj/zpj-skydrive-file.h
/usr/include/libzapojit-0.0/zpj/zpj-skydrive-folder.h
/usr/include/libzapojit-0.0/zpj/zpj-skydrive-photo.h
/usr/include/libzapojit-0.0/zpj/zpj-skydrive.h
/usr/include/libzapojit-0.0/zpj/zpj.h
/usr/lib64/libzapojit-0.0.so
/usr/lib64/pkgconfig/zapojit-0.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libzapojit/*
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjGoaAuthorizer.html
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjSkydrive.html
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjSkydriveEntry.html
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjSkydriveFile.html
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjSkydriveFolder.html
/usr/share/gtk-doc/html/libzapojit-0.0/ZpjSkydrivePhoto.html
/usr/share/gtk-doc/html/libzapojit-0.0/annotation-glossary.html
/usr/share/gtk-doc/html/libzapojit-0.0/authorization.html
/usr/share/gtk-doc/html/libzapojit-0.0/home.png
/usr/share/gtk-doc/html/libzapojit-0.0/index.html
/usr/share/gtk-doc/html/libzapojit-0.0/index.sgml
/usr/share/gtk-doc/html/libzapojit-0.0/ix01.html
/usr/share/gtk-doc/html/libzapojit-0.0/left.png
/usr/share/gtk-doc/html/libzapojit-0.0/libzapojit-0.0-ZpjAuthorizer.html
/usr/share/gtk-doc/html/libzapojit-0.0/libzapojit-0.0.devhelp2
/usr/share/gtk-doc/html/libzapojit-0.0/right.png
/usr/share/gtk-doc/html/libzapojit-0.0/skydrive.html
/usr/share/gtk-doc/html/libzapojit-0.0/style.css
/usr/share/gtk-doc/html/libzapojit-0.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzapojit-0.0.so.0
/usr/lib64/libzapojit-0.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzapojit/COPYING
